version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
    ports:
      - "8000:8000"
    env_file: .env
  frontend:
    image: ${DOCKER_USERNAME}/${DOCKER_FRONTEND_IMAGE}:latest
    ports:
      - "3000:80"
