version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    ports:
      - "8000:8000"
    env_file: .env
  frontend:
    image: ${DOCKER_USERNAME}/${DOCKER_FRONTEND_IMAGE}:${DOCKER_FRONTEND_IMAGE_TAG}
    ports:
      - "3000:80"
